[boris]
  version = 1

[build.submodules]
  command = [["dangling-refs"]]

[build.validate]
  command = [["validate-respect"]]

[build.dist-7-8]
  command = [
      ["master", "build", "dist-7-8", "-C", "x-aeson"]
    , ["master", "build", "dist-7-8", "-C", "x-attoparsec"]
    , ["master", "build", "dist-7-8", "-C", "x-bytestring"]
    , ["master", "build", "dist-7-8", "-C", "x-conduit"]
    , ["master", "build", "dist-7-8", "-C", "x-either"]
    , ["master", "build", "dist-7-8", "-C", "x-eithert"]
    , ["master", "build", "dist-7-8", "-C", "x-exception"]
    , ["master", "build", "dist-7-8", "-C", "x-htoml"]
    , ["master", "build", "dist-7-8", "-C", "x-optparse"]
    , ["master", "build", "dist-7-8", "-C", "x-show"]
    , ["master", "build", "dist-7-8", "-C", "x-templatehaskell"]
    , ["master", "build", "dist-7-8", "-C", "x-vector"]
    ]

[build.dist-7-10]
  command = [
      ["master", "build", "dist-7-10", "-C", "x-aeson"]
    , ["master", "build", "dist-7-10", "-C", "x-attoparsec"]
    , ["master", "build", "dist-7-10", "-C", "x-bytestring"]
    , ["master", "build", "dist-7-10", "-C", "x-conduit"]
    , ["master", "build", "dist-7-10", "-C", "x-either"]
    , ["master", "build", "dist-7-10", "-C", "x-eithert"]
    , ["master", "build", "dist-7-10", "-C", "x-exception"]
    , ["master", "build", "dist-7-10", "-C", "x-htoml"]
    , ["master", "build", "dist-7-10", "-C", "x-optparse"]
    , ["master", "build", "dist-7-10", "-C", "x-show"]
    , ["master", "build", "dist-7-10", "-C", "x-templatehaskell"]
    , ["master", "build", "dist-7-10", "-C", "x-vector"]
    ]

[build.branches-7-8]
  command = [
      ["master", "build", "branches-7-8", "-C", "x-aeson"]
    , ["master", "build", "branches-7-8", "-C", "x-attoparsec"]
    , ["master", "build", "branches-7-8", "-C", "x-bytestring"]
    , ["master", "build", "branches-7-8", "-C", "x-conduit"]
    , ["master", "build", "branches-7-8", "-C", "x-either"]
    , ["master", "build", "branches-7-8", "-C", "x-eithert"]
    , ["master", "build", "branches-7-8", "-C", "x-exception"]
    , ["master", "build", "branches-7-8", "-C", "x-htoml"]
    , ["master", "build", "branches-7-8", "-C", "x-optparse"]
    , ["master", "build", "branches-7-8", "-C", "x-show"]
    , ["master", "build", "branches-7-8", "-C", "x-templatehaskell"]
    , ["master", "build", "branches-7-8", "-C", "x-vector"]
    ]

[build.branches-7-10]
  command = [
      ["master", "build", "branches-7-10", "-C", "x-aeson"]
    , ["master", "build", "branches-7-10", "-C", "x-attoparsec"]
    , ["master", "build", "branches-7-10", "-C", "x-bytestring"]
    , ["master", "build", "branches-7-10", "-C", "x-conduit"]
    , ["master", "build", "branches-7-10", "-C", "x-either"]
    , ["master", "build", "branches-7-10", "-C", "x-eithert"]
    , ["master", "build", "branches-7-10", "-C", "x-exception"]
    , ["master", "build", "branches-7-10", "-C", "x-htoml"]
    , ["master", "build", "branches-7-10", "-C", "x-optparse"]
    , ["master", "build", "branches-7-10", "-C", "x-show"]
    , ["master", "build", "branches-7-10", "-C", "x-templatehaskell"]
    , ["master", "build", "branches-7-10", "-C", "x-vector"]
    ]
