[boris]
  version = 1


[build.dist-7-8-x-eithert]
  command = [["master", "build", "dist-7-8", "-C", "x-eithert"]]

[build.dist-7-8-x-optparse]
  command = [["master", "build", "dist-7-8", "-C", "x-optparse"]]

[build.dist-7-10-x-aeson]
  command = [["master", "build", "dist-7-10", "-C", "x-aeson"]]

[build.dist-7-10-x-attoparsec]
  command = [["master", "build", "dist-7-10", "-C", "x-attoparsec"]]

[build.dist-7-10-x-bytestring]
  command = [["master", "build", "dist-7-10", "-C", "x-bytestring"]]

[build.dist-7-10-x-conduit]
  command = [["master", "build", "dist-7-10", "-C", "x-conduit"]]

[build.dist-7-10-x-eithert]
  command = [["master", "build", "dist-7-10", "-C", "x-eithert"]]

[build.dist-7-10-x-exception]
  command = [["master", "build", "dist-7-10", "-C", "x-exception"]]

[build.dist-7-10-x-file-embed]
  command = [["master", "build", "dist-7-10", "-C", "x-file-embed"]]

[build.dist-7-10-x-htoml]
  command = [["master", "build", "dist-7-10", "-C", "x-htoml"]]

[build.dist-7-10-x-optparse]
  command = [["master", "build", "dist-7-10", "-C", "x-optparse"]]

[build.dist-7-10-x-show]
  command = [["master", "build", "dist-7-10", "-C", "x-show"]]

[build.dist-7-10-x-templatehaskell]
  command = [["master", "build", "dist-7-10", "-C", "x-templatehaskell"]]

[build.dist-7-10-x-vector]
  command = [["master", "build", "dist-7-10", "-C", "x-vector"]]

[build.dist-validate]
  command = [["validate-respect"]]


[build.branches-7-8-x-eithert]
  command = [["master", "build", "branches-7-8", "-C", "x-eithert"]]

[build.branches-7-8-x-optparse]
  command = [["master", "build", "branches-7-8", "-C", "x-optparse"]]

[build.branches-7-10-x-aeson]
  command = [["master", "build", "branches-7-10", "-C", "x-aeson"]]

[build.branches-7-10-x-attoparsec]
  command = [["master", "build", "branches-7-10", "-C", "x-attoparsec"]]

[build.branches-7-10-x-bytestring]
  command = [["master", "build", "branches-7-10", "-C", "x-bytestring"]]

[build.branches-7-10-x-conduit]
  command = [["master", "build", "branches-7-10", "-C", "x-conduit"]]

[build.branches-7-10-x-eithert]
  command = [["master", "build", "branches-7-10", "-C", "x-eithert"]]

[build.branches-7-10-x-exception]
  command = [["master", "build", "branches-7-10", "-C", "x-exception"]]

[build.branches-7-10-x-file-embed]
  command = [["master", "build", "branches-7-10", "-C", "x-file-embed"]]

[build.branches-7-10-x-htoml]
  command = [["master", "build", "branches-7-10", "-C", "x-htoml"]]

[build.branches-7-10-x-optparse]
  command = [["master", "build", "branches-7-10", "-C", "x-optparse"]]

[build.branches-7-10-x-show]
  command = [["master", "build", "branches-7-10", "-C", "x-show"]]

[build.branches-7-10-x-templatehaskell]
  command = [["master", "build", "branches-7-10", "-C", "x-templatehaskell"]]

[build.branches-7-10-x-vector]
  command = [["master", "build", "branches-7-10", "-C", "x-vector"]]


[build.all-submodules]
  command = [["dangling-refs"]]

[build.all-rebased]
  command = [["rebased"]]
