[master]
  runner = "s3://ambiata-dist/master-ambiata/master-haskell-multi-library-0.0.1-20151022072201-6e35303"
  version = 1
  sha1 = "87b3c0f85014087678bb96212a94cc1dcc14974d"

[build.dist]
  HADDOCK = "true"

[build.branches]
